library(argoFloats)
library(oce)
data("index")
index1 <- subset(index, id='1901584')
index2 <- subset(index1, cycle='124') 
profiles2 <- getProfiles(index2)
argos2 <- readProfiles(profiles2)
a <- argos2[[1]]
sigma <- swSigmaT(salinity=a[['salinity']], temperature=a[['temperature']], pressure=a[['pressure']], longitude=a[['longitude']], latitude=a[['latitude']])
diff <- abs(diff(sigma))
ifelse(diff > 0.03, TRUE, FALSE)
