---
title: "Introduction to argoFloats Flags"
author: "Dan Kelley (https://orcid.org/0000-0001-7808-5911) and Jaimie Harbin (https://orcid.org/0000-0003-3774-3732)"
date: "`r Sys.Date()`"
---

**Abstract**

# Introduction to Flags
Core, biogeochemical (BGC), and Deep Argo data all undergo testing to ensure the data found at the Data Assembly Centers are as accurate as possible. More specifically, testing in done in three levels:

1: Real time that complete checks on all measurements and assigned a quality flag within a 24-48 hour timeframe
2. Delayed mode
3. Regional scientific analyses of all float data with other available data. The procedures for regional analyses are still to be determined.

*Hypothesis* : Our hypothesis is that real-time data have all NAs for <PARAM>ADJUSTED, and we should therefore only use the <PARAM>ADJUSTED for delayed mode data.

# argoFloats and Flags

As described by the Argo user’s manual V3.3 [1], data that are given a flag value of 1, 2, 5, or 8 are considered 'good' data. If data are given a flag value of 9 (or missing value) they are not used, and flags 3, 5, 6, and 7 are considered 'bad' data. 

## Diagnostic Plot
Our `argoFloats` package takes flags into consideration and created a diagnostic plot. The diagnostic plot is a plot of parameter quality and paramter mean. This only works if `x` is an object that was created by `getProfiles()`. The user must also provide the `parameter` of interest. 

An example of how to get the diagnostic plot is as follows:

```{r, message=FALSE, warning=FALSE}
library(argoFloats)
data('indexSynthetic')
profiles <- getProfiles(indexSynthetic)
argos <- readProfiles(profiles)
plot(argos[[1]], which='diagnostic', parameter='oxygen')
```

## <PARAM>ADJUSTED

# References
[1] Carval, Thierry, Bob Keeley, Yasushi Takatsuki, Takashi Yoshida, Stephen Loch, Claudia Schmid, Roger Goldsmith et al. "Argo User's Manual, Version 3.2. December 29th 2015.[SUPERSEDED]." (2015).