language: r
warnings_are_errors: false
sudo: required

after_success:
    - Rscript -e 'library(covr);codecov()'

addons:
    apt:
        packages:
            - libnetcdf-dev
            - netcdf-bin

r_packages:
    - devtools
    - ncdf4
    - covr
    - sf
    - sp

r_github_packages:
    - codecov/example-r

env:
    global:
        - _R_CHECK_FORCE_SUGGESTS_=False
        - _R_CHECK_CRAN_INCOMING=False

