# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

addons:
    apt:
        packages:
            - libudunits2-dev
            - libnetcdf-dev
            - netcdf-bin

r_packages:
    - marmap
    - ncdf4
    - oce
    - ocedata
    - rgdal
    - sf

