# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
warnings_are_errors: false
cache: packages
after_success: travis_wait 30 Rscript -e 'library(covr); codecov(type="all")'

addons:
    apt:
        packages:
            - libgdal-dev
            - libudunits2-dev
            - libnetcdf-dev
            - netcdf-bin

r_packages:
    - shiny
    - shinycssloaders
    - marmap
    - ncdf4
    - oce
    - ocedata
    - rgdal
    - sf
    - covr
