library(argoFloats)
i <- getIndex("synthetic")
##is <- subset(i, ID="SR2902199")
##is <- subset(i, mode="delayed")
is <- subset(i, ID="2902199")
keep <- which(is[["profile"]] == 144)
iss <- subset(is, keep)
argos <- readProfiles(getProfiles(iss), handleFlags=!FALSE)
a <- argos[[1]] # now an oce object
summary(a)
o <- as.vector(a[["oxygen"]])
of <- as.vector(a[["oxygenFlag"]])
p <- as.vector(a[["pressure"]])
pf <- as.vector(a[["pressureFlag"]])
plot(o, p, ylim=rev(range(p, na.rm=TRUE)))
head(data.frame(o, of, p, pf))
