if (!interactive()) png("useAdjusted.png", unit="in", width=5, height=2.8, pointsize=11, res=150)
library(argoFloats)
data("index")
subset <- subset(index, ID='1901584')
profiles <- getProfiles(subset)
raw <- readProfiles(profiles)
adj <- useAdjusted(raw)
par(mfrow=c(1, 2))
oce::plotProfile(oce::as.ctd(raw[[1]]), xtype="temperature")
mtext("Raw data", side=3, line=-1, col=2)
oce::plotProfile(oce::as.ctd(adj[[1]]), xtype="temperature")
mtext("Adjusted data", side=3, line=-1, col=2)
if (!interactive()) dev.off()