if (!interactive()) png("useAdjusted.png", unit="in", width=7, height=3.92, pointsize=11, res=100)
library(argoFloats)
raw <- readProfiles(system.file("extdata", "SD5903586_001.nc", package="argoFloats"))
adj <- useAdjusted(raw)
par(mfrow=c(1,2), mar=c(5,4,1,2))
hist(raw[[1]][['oxygen']], xlab='Raw Oxygen', ylab="Frequency", main=NULL)
hist(adj[[1]][['oxygen']], xlab='Adjusted Oxygen', ylab="Frequency", main=NULL)
summary(unlist(raw[['oxygen']]))
summary(unlist(adj[['oxygen']]))
if (!interactive()) dev.off()