library(argoFloats)
library(oce)
item <- c("oxygen", "temperature", "salinity","pressure")
q <- function(x) 
    100 * (1 - sum(4 == x[['paste0(item),Flag']]) / length(x[['paste0(item)']]))
Mean <- function(x) 
    mean(x[['item']])
Min <- function(x)
    min(x[['item']])
Max <- function(x)
    max(x[['item']])
if (!exists("bai")) {
    bai <- getIndex(file='bgc')
    F5901462 <- subset(bai, ID='5901462') # Follow 5901462 float
    # Fraction of bad oxygen
    profiles <- getProfiles(F5901462)
    argos <- readProfiles(profiles, handleFlags=FALSE) 
}
time <- oce::numberAsPOSIXct(unlist(lapply(argos[['profile']], function(x) x[['time']])))
q <- unlist(lapply(argos[['profile']], q))
mean <- unlist(lapply(argos[['profile']], Mean))
min <- unlist(lapply(argos[['profile']], Min))
max <- unlist(lapply(argos[['profile']], Max))
par(mfrow=c(4,1))
oce.plot.ts(time,q, ylab="Oxygen Quality")
oce.plot.ts(time,mean, ylab="Oxygen Mean")
oce.plot.ts(time,min, ylab="Oxygen Minimum")
oce.plot.ts(time,max, ylab="Oxygen Maximum")
