if (!interactive()) pdf("01_sweeden.pdf", width=7, height=3.5, pointsize=11)
library(argoFloats)
if (!exists("ai"))
       ai <- getIndex()
index1 <- subset(ai, circle=list(longitude=-60.85,latitude=46.24, radius=200))
index2 <- subset(ai, circle=list(latitude=59.33, longitude=18.06, radius=100))
merge <- merge(index1,index2)
plot(merge)
if (!interactive()) dev.off()
