# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

name: R-CMD-check

jobs:
  R-CMD-check:
    #runs-on: macOS-latest
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      
      # dd: Using gfortran should be easier than this; however, modifying
      # ~/.R/Makevars doesn't appear to work in this context; nor does
      # ln -s with the library directory. This part of the action is
      # temporary and should be removed when CRAN oce can be used
      #DEK# - name: Link gfortran for devel oce 
      #DEK#   run: |
      #DEK#     ln -s `which gfortran-10` /usr/local/bin/gfortran
      #DEK#     gfortran --version || true
      #DEK#     ls /usr/local/Cellar/gcc | tail -n 1
      #DEK#     
      #DEK#     sudo mkdir -p /usr/local/gfortran
      #DEK#     sudo cp -r /usr/local/Cellar/gcc/`ls /usr/local/Cellar/gcc | tail -n 1`/lib/gcc/10 /usr/local/gfortran/lib
      #DEK#     sudo chmod 755 /usr/local/gfortran
      #DEK#     sudo chmod 755 /usr/local/gfortran/lib
      #DEK#     
      #DEK#     ls /usr/local/gfortran/lib || true
          
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "sf", "oce"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      ## A refresh of the cache can be forced by incrementing
      ## the number at the end of `key`. This should be done whenever
      ## the following step downloads new files or when the file format
      ## on the server might have changed.
      - name: Cache Argo downloads
        uses: actions/cache@v2
        with:
          path: ${{ runner.temp }}/argo-cache-dir
          key: argo-cache-dir-check-1
      - name: Ensure Argo cache directory exists
        env:
          R_ARGOFLOATS_DESTDIR: ${{ runner.temp }}/argo-cache-dir
        run: |
          if (!dir.exists(Sys.getenv("R_ARGOFLOATS_DESTDIR"))) {
            dir.create(Sys.getenv("R_ARGOFLOATS_DESTDIR"))
          }
        shell: Rscript {0}
      - name: Check
        env:
          R_ARGOFLOATS_DESTDIR: ${{ runner.temp }}/argo-cache-dir
          R_ARGOFLOATS_INDEX_AGE: "Inf"
          R_ARGOFLOATS_PROFILE_AGE: "Inf"
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
