# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      ## A refresh of the cache can be forced by incrementing
      ## the number at the end of `key`. This should be done whenever
      ## the following step downloads new files or when the file format
      ## on the server might have changed.
      - name: Cache Argo downloads
        uses: actions/cache@v2
        with:
          path: ${{ runner.temp }}/argo-cache-dir
          key: argo-cache-dir-check-1
      - name: Ensure Argo cache directory exists
        env:
          R_ARGOFLOATS_DESTDIR: ${{ runner.temp }}/argo-cache-dir
        run: |
          if (!dir.exists(Sys.getenv("R_ARGOFLOATS_DESTDIR"))) {
            dir.create(Sys.getenv("R_ARGOFLOATS_DESTDIR"))
          }
        shell: Rscript {0}
      - name: Check
        env:
          R_ARGOFLOATS_DESTDIR: ${{ runner.temp }}/argo-cache-dir
          R_ARGOFLOATS_INDEX_AGE: "Inf"
          R_ARGOFLOATS_PROFILE_AGE: "Inf"
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
